# 03_ Feature engineering


In this section, we perform feature engineering to transform raw variables into more informative features that improve model performance and interpretability.

Feature engineering helps:

- Capture hidden relationships in the data
- Improve predictive power
- Reduce noise
- Make variables more suitable for machine learning algorithms

***we import all the libraries that we need***

In [25]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, LabelEncoder,MinMaxScaler,StandardScaler
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
sns.set_style('whitegrid')

## Loading the data

In [33]:
anime_df = pd.read_csv('../data/processed/dataset_clean.csv')
display(anime_df.head())

,name,genre,type,episodes,rating,members,missing_episodes
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",movie,1.0,9.37,200630.0,0
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",tv,64.0,9.26,793665.0,0
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",tv,51.0,9.25,114262.0,0
3,Steins;Gate,"Sci-Fi, Thriller",tv,24.0,9.17,673572.0,0
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",tv,51.0,9.16,151266.0,0

In [27]:
anime_df['type'].unique()

array(['movie', 'tv', 'ova', 'special', 'music', 'ona'], dtype=object)

In [28]:
anime_df['genre'].unique()

array(['Drama, Romance, School, Supernatural',
       'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen',
       'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
       ..., 'Hentai, Sports', 'Drama, Romance, School, Yuri',
       'Hentai, Slice of Life'], dtype=object)

# Numeric features
now we scale the numeric features and standerize them

In [32]:
scaler = StandardScaler()
num_cols = ['episodes', 'members']
anime_df[num_cols] = scaler.fit_transform(anime_df[num_cols])

# Categorical features
we encode categorical features

In [30]:
type_dummies = pd.get_dummies(anime_df['type'], prefix='type')
anime_df = pd.concat([anime_df,type_dummies], axis = 1)
anime_df= anime_df.drop(columns=['type'])

In [31]:
display(anime_df.head())

,anime_id,name,genre,episodes,rating,members,missing_episodes,type_movie,type_music,type_ona,type_ova,type_special,type_tv
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",-0.242888,9.37,3.330241,0,True,False,False,False,False,False
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",1.101445,9.26,14.148406,0,False,False,False,False,False,True
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",0.824043,9.25,1.754713,0,False,False,False,False,False,True
3,9253,Steins;Gate,"Sci-Fi, Thriller",0.247900,9.17,11.957666,0,False,False,False,False,False,True
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",0.824043,9.16,2.429742,0,False,False,False,False,False,True

In [ ]:
anime_df.to_csv("../data/processed/dataset_ready.csv", index=False)