# 04_clustering

The objective of this step is to group anime into clusters based on their numerical and genre-based features. Clustering allows us to discover natural groupings in the data without using predefined labels.

***Import Required Libraries***

In [5]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

## Loading the data

In [8]:
DATA_PATH = "../data/processed/dataset_ready.csv"
anime_df = pd.read_csv(DATA_PATH)
anime_df.head()

,name,episodes,rating,members,missing_episodes,type_movie,type_music,type_ona,type_ova,type_special,...,genre_Shounen,genre_Shounen Ai,genre_Slice of Life,genre_Space,genre_Sports,genre_Super Power,genre_Supernatural,genre_Thriller,genre_Unknown,genre_Vampire
0,Kimi no Na wa.,-0.242888,9.37,3.330241,0,True,False,False,False,False,...,0,0,0,0,0,0,1,0,0,0
1,Fullmetal Alchemist: Brotherhood,1.101445,9.26,14.148406,0,False,False,False,False,False,...,1,0,0,0,0,0,0,0,0,0
2,Gintama°,0.824043,9.25,1.754713,0,False,False,False,False,False,...,1,0,0,0,0,0,0,0,0,0
3,Steins;Gate,0.247900,9.17,11.957666,0,False,False,False,False,False,...,0,0,0,0,0,0,0,1,0,0
4,Gintama&#039;,0.824043,9.16,2.429742,0,False,False,False,False,False,...,1,0,0,0,0,0,0,0,0,0

we must drop the column name since in clustering all values should be numeric

In [7]:
df = anime_df.drop(columns=['name'])
df.head()

,episodes,rating,members,missing_episodes,type_movie,type_music,type_ona,type_ova,type_special,type_tv,...,genre_Shounen,genre_Shounen Ai,genre_Slice of Life,genre_Space,genre_Sports,genre_Super Power,genre_Supernatural,genre_Thriller,genre_Unknown,genre_Vampire
0,-0.242888,9.37,3.330241,0,True,False,False,False,False,False,...,0,0,0,0,0,0,1,0,0,0
1,1.101445,9.26,14.148406,0,False,False,False,False,False,True,...,1,0,0,0,0,0,0,0,0,0
2,0.824043,9.25,1.754713,0,False,False,False,False,False,True,...,1,0,0,0,0,0,0,0,0,0
3,0.247900,9.17,11.957666,0,False,False,False,False,False,True,...,0,0,0,0,0,0,0,1,0,0
4,0.824043,9.16,2.429742,0,False,False,False,False,False,True,...,1,0,0,0,0,0,0,0,0,0