# 04_clustering

The objective of this step is to group anime into clusters based on their numerical and genre-based features. Clustering allows us to discover natural groupings in the data without using predefined labels.

***Import Required Libraries***

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

## Loading the data

In [2]:
DATA_PATH = "../data/processed/dataset_ready.csv"
anime_df = pd.read_csv(DATA_PATH)
anime_df.head()

,name,episodes,rating,members,missing_episodes,type_movie,type_music,type_ona,type_ova,type_special,...,genre_Shounen,genre_Shounen Ai,genre_Slice of Life,genre_Space,genre_Sports,genre_Super Power,genre_Supernatural,genre_Thriller,genre_Unknown,genre_Vampire
0,Kimi no Na wa.,-0.242888,2.845534,3.330241,0,True,False,False,False,False,...,0,0,0,0,0,0,1,0,0,0
1,Fullmetal Alchemist: Brotherhood,1.101445,2.737388,14.148406,0,False,False,False,False,False,...,1,0,0,0,0,0,0,0,0,0
2,Gintama°,0.824043,2.727556,1.754713,0,False,False,False,False,False,...,1,0,0,0,0,0,0,0,0,0
3,Steins;Gate,0.247900,2.648904,11.957666,0,False,False,False,False,False,...,0,0,0,0,0,0,0,1,0,0
4,Gintama&#039;,0.824043,2.639073,2.429742,0,False,False,False,False,False,...,1,0,0,0,0,0,0,0,0,0

we must drop the column name since in clustering all values should be numeric

In [3]:
df = anime_df.drop(columns=['name'])
df.head()

,episodes,rating,members,missing_episodes,type_movie,type_music,type_ona,type_ova,type_special,type_tv,...,genre_Shounen,genre_Shounen Ai,genre_Slice of Life,genre_Space,genre_Sports,genre_Super Power,genre_Supernatural,genre_Thriller,genre_Unknown,genre_Vampire
0,-0.242888,2.845534,3.330241,0,True,False,False,False,False,False,...,0,0,0,0,0,0,1,0,0,0
1,1.101445,2.737388,14.148406,0,False,False,False,False,False,True,...,1,0,0,0,0,0,0,0,0,0
2,0.824043,2.727556,1.754713,0,False,False,False,False,False,True,...,1,0,0,0,0,0,0,0,0,0
3,0.247900,2.648904,11.957666,0,False,False,False,False,False,True,...,0,0,0,0,0,0,0,1,0,0
4,0.824043,2.639073,2.429742,0,False,False,False,False,False,True,...,1,0,0,0,0,0,0,0,0,0

### Feature selection

In [11]:
genre_cols = [col for col in anime_df.columns if col.startswith('genre_')]
type_cols = [col for col in anime_df.columns if col.startswith('type_')]
core_numerical =['rating','members']
features = core_numerical + genre_cols
# here the matrix that we will use in the clustering 
x = anime_df[features].copy()

print(f"Clustering on {x.shape[1]} features")
print(f"Shape of X: {x.shape}")
print("\nColumns used:")
print(x.columns.tolist())

Clustering on 44 features
Shape of X: (12294, 44)

Columns used:
['rating', 'members', 'genre_Action', 'genre_Adventure', 'genre_Cars', 'genre_Comedy', 'genre_Dementia', 'genre_Demons', 'genre_Drama', 'genre_Ecchi', 'genre_Fantasy', 'genre_Game', 'genre_Harem', 'genre_Hentai', 'genre_Historical', 'genre_Horror', 'genre_Josei', 'genre_Kids', 'genre_Magic', 'genre_Martial Arts', 'genre_Mecha', 'genre_Military', 'genre_Music', 'genre_Mystery', 'genre_Parody', 'genre_Police', 'genre_Psychological', 'genre_Romance', 'genre_Samurai', 'genre_School', 'genre_Sci-Fi', 'genre_Seinen', 'genre_Shoujo', 'genre_Shoujo Ai', 'genre_Shounen', 'genre_Shounen Ai', 'genre_Slice of Life', 'genre_Space', 'genre_Sports', 'genre_Super Power', 'genre_Supernatural', 'genre_Thriller', 'genre_Unknown', 'genre_Vampire']